name: Api Mongoose V1

on: [push]
# Cuando se va a ejecutar este workflow

jobs:
# Stages -> los cprocesos de CI que tiene que hacer este workflow
# Este workflow tiene que hacer dos cosas:
  
  # Compilar -> build
  build:

    runs-on: ubuntu-latest
      # Nos dice en que sistema operativo se debe correrlo( se recomienda que sea algo linux, por los servers)
    steps:
      # Son los pasos que tengo que hacer para que build funcione
    - uses: actions/checkout@v2
      # Que version de Github actions va a ocupar
    - name: Build image Docker
      # Nombre el paso en el que estoy
    
    # run: docker build . --file Dockerfile --tag api-mongoose-v1
      # ejecuta un comando especifico
      run: npm install # esto por que no tenemos el Docker aun yo Emma

  # Test
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Tests API
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
    - run: npm test
